In [1]:
import numpy as np

In [2]:
matrix_a = [[1,2,3,4]]

# create a vector (numpy vector)
nV = np.array(matrix_a)
print(nV), print(' ')

#transpose form
print(nV.T), print(' ')

# transpose form of the transposed
nVT = nV.T
print(nVT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [3]:
matrix_a = [
    [1,2,3,4],
    [5,6,7,8]
]

# create a matrix (numpy matrix)
nM = np.array(matrix_a)
print(nM), print(' ')

# transpose form
print(nM.T), print(' ')

# transpose form of the transposed
nMT = nM.T
print(nMT.T), print(' ')


[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]
 


(None, None)

In [4]:
# exampine data types

print(f'type of tV {type(nV)}')
print(f'type of tM {type(nM)}')

type of tV <class 'numpy.ndarray'>
type of tM <class 'numpy.ndarray'>


In [5]:
# create random matrixes
A = np.random.randn(3, 4) # random Normal distribution
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

# try some multiplications
print(np.round(A@B, 2)), print(' ')
print(np.round(C.T@A, 2)), print(' ')

[[ 2.45 -0.18 -1.78 -1.27 -0.42]
 [-5.1  -3.63 -2.04 -1.45 -0.66]
 [ 4.27 -2.98 -5.56 -3.78 -0.03]]
 
[[ 1.99 -0.87  2.03 -0.28]
 [ 0.29 -1.8   0.34  0.63]
 [-3.69  1.16 -0.83  0.18]
 [ 0.35 -2.09  0.68  0.68]
 [ 0.01  0.97  4.21 -1.14]
 [-0.89  3.    2.82 -1.59]
 [-0.34 -0.26 -2.06  0.51]]
 


(None, None)

In [6]:
# print(np.round(A@C, 2)), print(' ')
print(np.round(B@C, 2)), print(' ')

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [ ]:
# argmin, argmax

# create a vector
v = [ 1,40, 2, -3]

minval = np.min(v)
maxval = np.max(v)

print('Min, max: %g, %g' %(minval, maxval))

minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min, max indices : %g, %g' %(minidx, maxidx))

Min, max: -3, 40
Min, max indices : 3, 1


In [ ]:
# repeat with matrix

M = np.array([
    [0 ,1, 10],
    [20,8, 5]
])

print(M), print(' ')

# there are various minima in this matrix
minvals1 = np.min(M) # minimum for entire matrix
minvals2 = np.min(M, axis = 0) # minimum of each column 
minvals3 = np.min(M, axis = 1) # minimum of each row

print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


In [ ]:
# get minimum values' indices
minidx1 = np.argmin(M)
minidx2 = np.argmin(M, axis = 0)
minidx3 = np.argmin(M, axis = 1)

print(M), print(' ')
print(minidx1)
print(minidx2)
print(minidx3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 0 1]
[0 2]


# random seed

In [ ]:
# random seed mechanism (random State)

randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(2020)

print(randseed1.randn(3))
# print(randseed2.randn(3))
# ----------------------------
print(randseed1.randn(3))
# print(randseed2.randn(3))
# ----------------------------
print(randseed1.randn(3))
# print(randseed2.randn(3))
# ----------------------------
print(randseed1.randn(3))
# print(randseed2.randn(3))
# ----------------------------
print(randseed1.randn(3))
# print(randseed2.randn(3))

# trying running this code multiple times

# the more we call randseed1 from the starting INITIAL POINT "random state"
# there will be more new arrays generated

[ 0.27626589 -1.85462808  0.62390111]
[1.14531129 1.03719047 1.88663893]
[-0.11169829 -0.36210134  0.14867505]
[-0.43778315  2.171257    1.15231025]
[-1.81881234 -0.13804934  0.53983961]


In [ ]:
print(randseed1.randn(3))
print(randseed2.randn(3))
# ----------------------
print(randseed1.randn(3))
print(randseed2.randn(3))

# since we're not calling these randomseed from the starting point "random state", 
# there will always be new arrays

[-0.67570259  1.31351616  0.9033747 ]
[ 1.15932373  0.6565008  -0.49106094]
[-2.09812613 -0.25777416  1.02362483]
[ 0.15943828 -0.25876601 -0.42051825]


In [ ]:
# using randomState is called LOCAL RANDOM, 
# the most used can be GLOBAL RANDOM SEED but is is hard it scope it
np.random.seed(17)
print(np.random.randn(3))
print(np.random.randn(3))
print(np.random.randn(3))

# calling multiple times from the starting INITIAL POINT "random.seed"
# the more we call, the more random arrays will be generated

[ 0.27626589 -1.85462808  0.62390111]
[1.14531129 1.03719047 1.88663893]
[-0.11169829 -0.36210134  0.14867505]


In [ ]:
print(np.random.randn(3))
# as we call this not from the INITIAL POINT "random.seed"
# there will always be new arrays are generated

[ 0.15999085 -0.75522304  0.34989599]


# extracting some samples from a NUMPY array

In [2]:
testArr = np.array([3,6,6,98,53,88,00,1,9,12,1,47,13])
testArr[range(10)]

array([ 3,  6,  6, 98, 53, 88,  0,  1,  9, 12])

In [3]:
indicesArr = [0,1,2]
testArr[indicesArr]

array([3, 6, 6])

In [4]:
# randomly chose items from an array

chosen_items_indices = np.random.choice(
    a=range(0, 10), # an array or a sequence for sample from
    size=5, # number of samples to draw (to get out of)
    replace= False, # if "True" the same element can be sample multiple times
)

print(chosen_items_indices)
print(testArr[chosen_items_indices])

[1 4 3 7 6]
[ 6 53 98  1  0]


In [6]:
# choosing items using 'True', 'False'

# now let's revise a little
indicesArr = np.array([1, 1, 1, 1, 1])
testArr = np.array([1,2,3,4,5])
testArr[indicesArr]

array([2, 2, 2, 2, 2])

In [9]:
# choosing items using 'True', 'False'
booleanArr = np.array([True, False, True, False, True])
testArr = np.array([1,2,3,4,5])
testArr[~booleanArr]

array([2, 4])