In [1]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))

True
1
NVIDIA GeForce RTX 3050 Laptop GPU


In [ ]:
# avoid crashing when importing pytroch.nn deep learning

# a way to make pytorch not crashing the python kernel in jupyter notebook
# probally not have to do this in the newest version of cuda.

# import os
# os.environ['KMP_DUPLICATE_LIB_OK']='True' 

In [ ]:
# ----------------------- HOW TO MAKE PYTORCH USE GPU --------------------------

# at beginning of the script
# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# ...

# then whenever you get a new Tensor or Module
# this won't copy if they are already on the desired device
# input = data.to(device)
# model = MyModule(...).to(device)

In [2]:
matrix_a = [
    [1,2,3,4]
]

# create a vector (torch vector) 
tV = torch.tensor(matrix_a)
print(tV), print(' ')

# get the transpose form
print(tV.T), print(' ')

# get the transpose form of the tranposed
tVT = tV.T
print(tVT.T)


tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [3]:
# create a matrix (torch matrix)

matrix_a = [
    [1,2,3,4],
    [5,6,7,8]
]

# create a matrix (torch matrix)
tM = torch.tensor(matrix_a)
print(tM), print(' ')

# get the transpose form
print(tM.T), print(' ')

# get the transpose form of the transposed
tMT = tM.T
print(tMT.T), print(' ')

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 


(None, None)

In [4]:
# exampine data types

print(f'type of tV {type(tV)}')
print(f'type of tM {type(tM)}')

# in pytorch: all scaler, array, vector, matrix, tensor are seen as "tensor"

type of tV <class 'torch.Tensor'>
type of tM <class 'torch.Tensor'>


In [5]:
# create random matrices

A = torch.randn(3, 4)
B = torch.randn(4, 5)

import numpy as np

C1 = np.random.randn(4, 7) # numpy matrix
C2 = torch.tensor(C1, dtype=torch.float) # convert C1 numpy matrix into a pytorch tensor 

In [6]:
# print(np.round(A@B, 2)), print(' ')
# print(np.round(A@C1, 2)), print(' ')
print(np.round(A@C2, 2)), print(' ')

tensor([[-1.0600, -1.0700,  1.8700,  2.9200, -1.3100, -0.6300, -1.2000],
        [-0.5300, -1.8200, -0.2700, -0.1600, -0.8900, -0.9000,  1.5400],
        [-2.1800,  0.2500,  0.7300, -0.5200,  1.2900,  2.0700, -0.7600]])
 


(None, None)

In [7]:
# argmin, argmax

v = torch.tensor([1,40, 2, -3])

minval = torch.min(v)
maxval = torch.max(v)

print('Min, max: %g, %g ' %(minval, maxval))

minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('min, max indices: %g,%g ' %(minidx, maxidx))

Min, max: -3, 40 
min, max indices: 3,1 


In [8]:
# now for the mmatrix

M = torch.tensor([
    [20 ,1, 10],
    [0,8, 5]
])

min1 = torch.min(M)
min2 = torch.min(M, axis = 0)
min3 = torch.min(M, axis = 1)

min1idx = torch.argmin(M)
print(min1)
print(min1idx)

tensor(0)
tensor(3)


In [9]:
print(min2)
print(min2.values)
print(min2.indices)

torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([1, 0, 1]))
tensor([0, 1, 5])
tensor([1, 0, 1])


# random seed

In [17]:
# pytorch only use GLOBAL RANDOM SEED

torch.randn(5)

tensor([1.2012, 0.7507, 0.0372, 1.4131, 0.6942])

In [11]:
torch.manual_seed(17)
print(torch.randn(5)) # the first randomcall from the starting point "seed" will always be the same

# torch seed doesn't spread to numpy
print(np.random.randn(5))

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 1.07561582 -1.35337436 -0.39129284  1.070874    1.18375495]
